// src/vue/axe-linter-vue/src/components/AriaProps.vue
<template>
  <div>
    <div class="AriaPropsSucceed">
      <input aria-labelledby="address_label" />
    </div>
    <div class="AriaPropsFailed">
      <input aria-labeledby="address_label" /> <!-- Bad: Labeled using incorrectly spelled aria-labeledby -->
    </div>
  </div>
</template>

<script>
export default {
  name: "AriaProps"
};
</script>

// src/tsx/axe-linter-tsx/src/components/aria-props.tsx
import React from 'react'

const AriaPropsSucceed: React.FC = () => (
  <div>
    <div id="address_label">Enter your address</div>
    <input aria-labelledby="address_label"></input>
  </div>
);

const AriaPropsFailed: React.FC = () => (
  <div>
    <div id="address_label">Enter your address</div>
    <input aria-labeledby="address_label"></input>
  </div>
);

const AriaProps: React.FC = () => (
  <div>
    <AriaPropsSucceed />
    <AriaPropsFailed />
  </div>
);

export default AriaProps
