// src/vue/axe-linter-vue/src/components/NoRedundantRoles.vue
<template>
  <div>
    <div class="NoRedunantRolesSucceed">
      <div />
      <button role="presentation" />
    </div>
    <div class="NoRedunantRolesFailed">
      <button role="button" />
      <img role="img" src="foo.jpg"/>
    </div>
  </div>
</template>

<script>
export default {
  name: "NoRedunantRoles"
}
</script>

// src/jsx/axe-linter-jsx/src/components/no-redundant-roles.jsx
import React from "react";

const NoRedundantRolesSucceed = () => (
  <div>
    <div />
    <button role="presentation" />
    <MyComponent role="main" />
  </div>
);

const NoRedundantRolesFailed = () => (
  <div>
    <button role="button" />
    <img role="img" src="foo.jpg" />
  </div>
);

const NoRedundantRoles = () => (
  <div>
    <NoRedundantRolesSucceed />
    <NoRedundantRolesFailed />
  </div>
);

export default NoRedundantRoles;
