// src/vue/axe-linter-vue/src/components/RoleHasRequiredAriaProps.vue
<template>
  <div>
    <div class="RoleHasRequiredAriaPropsSucceed">
      <span role="checkbox" aria-checked="false" aria-labelledby="foo" tabindex="0"></span>
    </div>
    <div class="RoleHasRequiredAriaPropsFailed">
      <span role="checkbox" aria-labelledby="foo" tabindex="0"></span>
    </div>
  </div>
</template>

<script>
export default {
  name: "RoleHasRequiredAriaProps"
}
</script>

// src/jsx/axe-linter-jsx/src/components/role-has-required-aria-props.jsx
import React from "react";

const RoleHasRequiredAriaPropsSucceed = () => (
  <div>
    {/* <!-- Good: the checkbox role requires the aria-checked state --> */}
    <span
      role="checkbox"
      aria-checked="false"
      aria-labelledby="foo"
      tabindex="0"
    ></span>
  </div>
);

const RoleHasRequiredAriaPropsFailed = () => (
  <div>
    {/* <!-- Bad: the checkbox role requires the aria-checked state --> */}
    <span role="checkbox" aria-labelledby="foo" tabindex="0"></span>
  </div>
);

const RoleHasRequiredAriaProps = () => (
  <div>
    <RoleHasRequiredAriaPropsSucceed />
    <RoleHasRequiredAriaPropsFailed />
  </div>
);

export default RoleHasRequiredAriaProps;
