// src/jsx/axe-linter-jsx/src/components/anchor-has-content.jsx
import React from "react";

const AnchorHasContentSucceed = () => (
  <div>
    <a>Anchor Content!</a>
    <a>
      <TextWrapper />
    </a>
    <a dangerouslySetInnerHTML={{ __html: "foo" }} />
  </div>
);

const AnchorHasContentFailed = () => (
  <div>
    <a />
    <a>
      <TextWrapper aria-hidden />
    </a>
  </div>
);

const AnchorHasContent = () => (
  <div>
    <AnchorHasContentSucceed />
    <AnchorHasContentFailed />
  </div>
);

export default AnchorHasContent;

// src/vue/axe-linter-vue/src/components/AnchorHasContent.vue
<template>
  <div>
    <div class="AnchorHasContentSucceed">
      <a>Anchor Content!</a>
      <a><TextWrapper /><a>
      <a is="TextWrapper" />
      <a v-text="msg" />
      <a v-html="msg" />
    </div>
    <div class="AnchorHasContentFailed">
      <a />
      <a><TextWrapper aria-hidden /></a>
    </div>
  </div>
</template>

<script>
export default {
  name: "AnchorHasContent"
};
</script>
