// src/jsx/axe-linter-jsx/src/components/aria-role.jsx
import React from "react";

const AriaRoleSucceed = () => (
  <div>
    <div role="button"></div>
    <div role={role}></div>
    <div></div>
    <Foo role={role}></Foo>
  </div>
);

const AriaRoleFailed = () => (
  <div>
    <div role="datepicker"></div> <div role="range"></div>
    <div role=""></div> <Foo role={role}></Foo>
  </div>
);

const AriaRole = () => (
  <div>
    <AriaRoleSucceed />
    <AriaRoleFailed />
  </div>
);

export default AriaRole;

// src/vue/axe-linter-vue/src/components/AriaRole.vue
<template>
  <div>
    <div class="AriaRoleSucceed">
      <div role="button"></div>     <!-- Good: "button" is a valid ARIA role -->
      <div :role="role"></div>       <!-- Good: role is a variable & cannot be determined until runtime. -->
      <div></div>                   <!-- Good: No ARIA role -->
      <Foo role={role}></Foo>       <!-- Good: ignoreNonDOM is set to true -->
    </div>
    <div class="AriaRoleFailed">
      <div role="datepicker"></div> <!-- Bad: "datepicker" is not an ARIA role -->
      <div role="range"></div>      <!-- Bad: "range" is an _abstract_ ARIA role -->
    </div>
  </div>
</template>

<script>
export default {
  name: "AriaRole",
  props: {
    role: String
  }
};
</script>
