// src/jsx/axe-linter-jsx/src/components/iframe-has-title.jsx
import React from "react";

const IframeHasTitleSucceed = () => (
  <div>
    <iframe title="This is a unique title" />
    <iframe title={uniqueTitle} />
  </div>
);

const IframeHasTitleFailed = () => (
  <div>
    <iframe />
    <iframe {...props} />
    <iframe title="" />
    <iframe title={""} />
    <iframe title={``} />
    <iframe title={undefined} />
    <iframe title={false} />
    <iframe title={true} />
    <iframe title={42} />
  </div>
);

const IframeHasTitle = () => (
  <div>
    <IframeHasTitleSucceed />
    <IframeHasTitleFailed />
  </div>
);

export default IframeHasTitle;

// src/vue/axe-linter-vue/src/components/IframeHasTitle.vue
<template>
  <div>
    <div class="IframeHasTitleSucceed">
      <iframe title="This is a unique title" />
      <iframe title={uniqueTitle} />
    </div>
    <div class="IframeHasTitleFailed">
      <iframe />
      <iframe title="" />
    </div>
  </div>
</template>

<script>
export default {
  name: "IframeHasTitle",
  props: {
    uniqueTitle: String
  }
};
</script>
