// src/jsx/axe-linter-jsx/src/components/media-has-caption.jsx
import React from "react";

const MediaHasCaptionSucceed = () => (
  <div>
    <audio>
      <track kind="captions" {...props} />
    </audio>
    <video>
      <track kind="captions" {...props} />
    </video>
    <video muted {...props}></video>
  </div>
);

const MediaHasCaptionFailed = () => (
  <div>
    <audio {...props} />
    <video {...props} />
  </div>
);

const MediaHasCaption = () => (
  <div>
    <MediaHasCaptionSucceed />
    <MediaHasCaptionFailed />
  </div>
);

export default MediaHasCaption;

// src/vue/axe-linter-vue/src/components/MediaHasCaption.vue
<template>
  <div>
    <div class="MediaHasCaptionSucceed">
      <audio><track kind="captions" /></audio>
      <video><track kind="captions" /></video>
      <video muted ></video>
    </div>
    <div class="MediaHasCaptionFailed">
      <audio />
      <video />
    </div>
  </div>
</template>

<script>
export default {
  name: "MediaHasCaption"
}
</script>
