// src/jsx/axe-linter-jsx/src/components/no-autofocus.jsx
import React from "react";

const NoAutofocusSucceed = () => (
  <div>
    <div />
  </div>
);

const NoAutofocusFailed = () => (
  <div>
    <div  />
    <div  />
    <div  />
    <div  />
  </div>
);

const NoAutofocus = () => (
  <div>
    <NoAutofocusSucceed />
    <NoAutofocusFailed />
  </div>
);

export default NoAutofocus;

// src/vue/axe-linter-vue/src/components/NoAutoFocus.vue
<template>
  <div>
    <div class="NoAutoFocusSucceed">
      <div />
    </div>
    <div class="NoAutoFocusFailed">
      <input autofocus="autofocus" />
      <div autoFocus />
      <div autoFocus="true" />
      <div autoFocus="false" />
      <div autoFocus={undefined} />
    </div>
  </div>
</template>

<script>
export default {
  name: "NoAutoFocus"
}
</script>
