// src/jsx/axe-linter-jsx/src/components/no-onchange.jsx
import React from "react";

const NoOnchangeSucceed = () => (
  <div>
    <select onBlur={updateModel}>
      <option />
    </select>

    <select>
      <option onBlur={handleOnBlur} onChange={handleOnChange} />
    </select>
  </div>
);

const NoOnchangeFailed = () => (
  <div>
    <select onChange={updateModel} />
  </div>
);

const NoOnchange = () => (
  <div>
    <NoOnchangeSucceed />
    <NoOnchangeFailed />
  </div>
);

export default NoOnchange;

// src/vue/axe-linter-vue/src/components/NoOnChange.vue
<template>
  <div>
    <div class="NoOnChangeSucceed">
      <select onBlur={updateModel}>
        <option/>
      </select>

      <select @blur="updateModel">
        <option/>
      </select>

      <select>
        <option onBlur={handleOnBlur} onChange={handleOnChange} />
      </select>
    </div>
    <div class="NoOnChangeFailed">
      <select onChange={updateModel} />
    </div>
  </div>
</template>

<script>
export default {
  name: "NoOnChange"
}
</script>
